website/forms/CreateProjectForm.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, IntegerField, TextAreaField
from wtforms.validators import DataRequired, Optional, NumberRange


class CreateProjectForm(FlaskForm):
    name = StringField('Имя проекта', validators=[DataRequired()])
    max_members = IntegerField('Максимальное число участников:', validators=[DataRequired(), NumberRange(min=1)])
    description =  TextAreaField('Введите описание:', validators=[Optional()])
    submit = SubmitField('Подтвердить')

website/forms/LoginForm.py
from flask_wtf import FlaskForm
from wtforms import PasswordField, BooleanField, SubmitField, EmailField
from wtforms.validators import DataRequired


class LoginForm(FlaskForm):
    email = EmailField('Почта', validators=[DataRequired()])
    password = PasswordField('Пароль', validators=[DataRequired()])
    remember_me = BooleanField('Запомнить меня')
    submit = SubmitField('Войти')

website/auth.py
from flask import Blueprint, render_template, redirect, url_for, abort, flash, current_app
from flask_login import login_user, login_required, logout_user, current_user
from .forms.LoginForm import LoginForm
from .forms.RegisterForm import RegisterForm
from data import db_session
from data.users import User


auth = Blueprint("auth", __name__, template_folder="../templates")


# Авторизация
@auth.route("/login", methods=['GET', 'POST'])
def login():
    if not current_user.is_anonymous:
        abort(404)
    form = LoginForm()
    if form.validate_on_submit():
        db_sess = db_session.create_session()
        user = db_sess.query(User).filter(User.email == form.email.data).first()
        if user and user.check_password(form.password.data):
            login_user(user, remember=form.remember_me.data)
            current_app.logger.info(f"User has logged in: {current_user}")
            flash("Вы вошли в аккаунт!", category="success")
            return redirect(url_for('views.home'))
        flash("Неправильный логин или пароль.", category="error")
    return render_template("login.html", title='Авторизация', form=form, user=current_user)


# Регистрация
@auth.route("/sign-up", methods=['GET', 'POST'])
def sign_up():
    if not current_user.is_anonymous:
        abort(404)
    form = RegisterForm()
    if form.validate_on_submit():
        if form.password.data != form.password_again.data:
            flash("Пароли не совпадают!", "warning")
            return render_template("signup.html", title='Регистрация', form=form, user=current_user)
        db_sess = db_session.create_session()
        if db_sess.query(User).filter(User.email == form.email.data).first():
            flash("Такой пользователь уже есть!", "warning")
            return render_template("signup.html", title='Регистрация', form=form, user=current_user)
        user = User(
            name=form.name.data,
            email=form.email.data
        )
        user.set_password(form.password.data)
        db_sess.add(user)
        db_sess.commit()
        current_app.logger.info(f"New user has registered: {user}")
        flash("Вы зарегистрированы!", "success")
        return redirect(url_for('auth.login'))
    return render_template("signup.html", title='Регистрация', form=form, user=current_user)


# Выход из аккаунта
@auth.route('/logout')
@login_required
def logout():
    current_app.logger.info(f"User logged out: {current_user}")
    logout_user()
    flash("Вы вышли из аккаунта")
    return redirect("/")

website/views.py
from flask import Blueprint, render_template, abort, request, url_for, redirect
from flask_login import login_required, current_user
from data import db_session
from data.users import User
from data.projects import Project
from .forms.CreateProjectForm import CreateProjectForm


views = Blueprint("views", __name__, template_folder="../templates")


@views.route("/")
@views.route("/home")
def home():
    db_sess = db_session.create_session()
    projects = db_sess.query(Project).all()

    return render_template("home.html", title='Менеджер проектов', projects=projects, user=current_user)

@views.route("/create-project", methods=['GET', 'POST'])
@login_required
def create_project():
    form = CreateProjectForm()
    
    if form.validate_on_submit():
        db_sess = db_session.create_session()
        user = db_sess.query(User).get(current_user.id)
        
        project = Project(
            name=form.name.data,
            max_members=form.max_members.data,
            description=form.description.data
        )
        project.set_leader(user)
        
        db_sess.add(project)
        db_sess.commit()
        
        return redirect(url_for("views.home"))
    
    return render_template("create_project.html", page_header="Создание проекта", form=form, user=current_user)    


@views.route("/join-project/<int:project_id>")
@login_required
def join_project(project_id):
    db_sess = db_session.create_session()
    project = db_sess.query(Project).get(project_id)
    user = db_sess.query(User).get(current_user.id)
    
    if not project:
        abort(404)
    
    if user in project.members or len(project.members) == project.max_members:
        abort(404)
    
    project.add_member(user)
    db_sess.commit()

    return redirect(url_for("views.home"))


@views.route("/leave-project/<int:project_id>")
def leave_project(project_id):
    db_sess = db_session.create_session()
    project = db_sess.query(Project).get(project_id)
    
    if not project:
        abort(404)
    
    if current_user.id == project.leader_id:
        abort(404)
    
    user = db_sess.query(User).get(current_user.id)
    user.projects.remove(project)
    db_sess.commit()
    return redirect(url_for("views.my_projects"))


@views.route("/delete-project/<int:project_id>")
def delete_project(project_id):
    db_sess = db_session.create_session()
    project = db_sess.query(Project).get(project_id)
    
    if not project:
        abort(404)
    
    if current_user.id != project.leader_id:
        abort(404)
    
    db_sess.delete(project)
    db_sess.commit()
    return redirect(url_for("views.my_projects"))


@views.route("/my-projects")
@login_required
def my_projects():
    db_sess = db_session.create_session()
    user = db_sess.query(User).get(current_user.id)
    print(user.projects)
    return render_template("my_projects.html", projects=user.projects, title="Мои проекты", user=current_user)


@views.route("/edit-project/<int:project_id>", methods=['GET', 'POST'])
@login_required
def edit_project(project_id):
    form = CreateProjectForm()
    
    db_sess = db_session.create_session()
    project = db_sess.query(Project).get(project_id)
    user = db_sess.query(User).get(current_user.id)
    
    if not project:
        abort(404)
    
    if user.id != project.leader_id:
        abort(404)
    
    if form.validate_on_submit():
        project.name = form.name.data
        project.max_members = form.max_members.data
        project.description = form.description.data
        
        db_sess.commit()
        return redirect(url_for("views.my_projects"))
    
    form.name.data = project.name
    form.max_members.data = project.max_members
    form.description.data = project.description
    
    return render_template("create_project.html", page_header="Редактирование проекта", title="Редактирование проекта", form=form, user=current_user)


@views.route("/view-project/<int:project_id>")
@login_required
def view_project(project_id):
    db_sess = db_session.create_session()
    project = db_sess.query(Project).get(project_id)
    user = db_sess.query(User).get(current_user.id)
    
    if not project:
        abort(404)
    
    if user not in project.members:
        abort(404)
    
    return render_template("view_project.html", prj=project, title="Просмотр проекта", user=current_user)


@views.route("/delete-member/<int:project_id>/<int:member_id>")
@login_required
def delete_member(project_id, member_id):
    db_sess = db_session.create_session()
    project = db_sess.query(Project).get(project_id)
    member = db_sess.query(User).get(member_id)
    user = db_sess.query(User).get(current_user.id)
    
    if not project or not member:
        abort(404)
    
    if member.id == user.id:
        abort(404)
    
    if user.id != project.leader_id:
        abort(404)
    
    if member not in project.members:
        abort(404)
    
    project.members.remove(member)
    db_sess.commit()
    
    return redirect(url_for("views.view_project", project_id=project_id))

templates/base.html
{% from "components/toast.html" import toast %}
{% from "components/user_avatar.html" import user_avatar %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" href="{{url_for('static', filename='img/icon/favicon.ico')}}" sizes="48x48" type="image/x-icon">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/style.css')}}" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">
    <title>{{title}}</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light" style="z-index: 11;">
        <div class="container-fluid">
          <a class="navbar-brand" id="site_logo" href="{{url_for('views.home')}}"><img src="{{url_for('static', filename='img/site_logo.png')}}" style="width: 150px; height: 27px;"alt="logo"></a>
  
          <button 
            class="navbar-toggler"
            type="button"
            data-bs-toggle="collapse"
            data-bs-target="#my_navbar">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse flex-grow-1" id="my_navbar">
            <div class="navbar-nav ms-auto flex-nowrap text-end">
              {% if user.is_authenticated %}
                <a class="nav-item nav-link menu-item" href="{{url_for('views.create_project')}}">Создать проект</a>
                <div class="dropdown">
                  <a class="nav-item nav-link" role="button" id="dropdownMenuLink" data-bs-toggle="dropdown" aria-expanded="false"><div class="d-flex align-items-center justify-content-end">
                    <div>{{user.name}}</div>
                    <div>⠀</div>
                    <div>{{user_avatar(user.id, 25)}}</div>
                  </div></a>
                  <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="dropdownMenuLink">
                    <li><a class="dropdown-item" href=""><i class="bi bi-person-circle"></i> Профиль</a></li>
                    <li><a class="dropdown-item" href="{{url_for('views.my_projects')}}">Мои проекты</a></li>
                    <li><hr class="dropdown-divider"></li>
                    <li><a class="dropdown-item" href="{{url_for('auth.logout')}}"><i class="bi bi-box-arrow-right"></i> Выйти</a></li>
                  </ul>
                </div>
              {% else %}
                <a class="nav-item nav-link menu-item" href="{{url_for('auth.login')}}">Login</a>
                <a class="nav-item nav-link menu-item" href="{{url_for('auth.sign_up')}}">Sign Up</a>
              {% endif %}
            </div>
          </div>
        </div>
      </nav>
      {% with messages = get_flashed_messages(with_categories=True) %}
        {% if messages %}
        <div aria-live="polite" aria-atomic="true" class="position-relative">
          <div class="toast-container position-absolute top-0 end-0 p-3">
          {% for category, message in messages %}
            {{ toast(message=message, category=category) }}
          {% endfor %}
        </div>
      </div>
        {% endif %}
      {% endwith %}
      <div class="container" style="margin-top: 20px;">{% block content %} {% endblock %}</div>
</body>
</html>

templates/create_project.html
{% extends "base.html" %}

{% block content %}
<div class="row">
    <div class="col-lg-5 col-sm-7 mx-auto">
    <form method="POST">
        <h3 align="center">{{page_header}}</h3>
        {{ form.hidden_tag() }}
        <p>
            {{ form.name.label }}<br>
            {{ form.name(class="form-control") }}<br>
            {% for error in form.name.errors %}
                <div class="alert alert-danger" role="alert">
                    {{ error }}
                </div>
            {% endfor %}
        </p>
        <p>
            {{ form.max_members.label }}<br>
            {{ form.max_members(class="form-control") }}<br>
            {% for error in form.max_members.errors %}
                <div class="alert alert-danger" role="alert">
                    {{ error }}
                </div>
            {% endfor %}
        </p>
        <p>
            {{ form.description.label }}<br>
            {{ form.description(class="form-control") }}<br>
            {% for error in form.description.errors %}
                <div class="alert alert-danger" role="alert">
                    {{ error }}
                </div>
            {% endfor %}
        </p>
        <p>{{ form.submit(type="submit", class="btn btn-success mx-auto d-block col-lg-3 col-sm-5") }}</p>
</form>
</div>
</div>

{% endblock %}

templates/home.html
{% extends "base.html" %}
{% from "components/project_card.html" import project_card %}

{% block content %}
    {% if projects %}
    {% for prj in projects %}
    
    <div class="row" style="margin-bottom: 20px;">
        <div class="col-sm-8 mx-auto">
            {{project_card(prj)}}
            <div class="col-lg-3" style="margin-left: 10px; margin-top: 5px;">
            {% if user.is_authenticated %}

                {% if user in prj.members %}
                    <a class="btn btn-success disabled" href="">Вы учавствуете!</a>
                {% elif prj.members|length == prj.max_members %}
                    <a class="btn btn-primary disabled" href="">Нет мест!</a>
                {% elif prj.leader_id != user.id %}
                    <a class="btn btn-success" href="{{url_for('views.join_project', project_id=prj.id)}}">Присоединиться</a>
                {% endif %}
            {% endif %}
            </div>
        </div>
    </div>

    {% endfor %}
    {% else %}
    <div class="row">
        <h5 class="text-muted" style="text-align: center">На площадке пока что нет ни одного проекта, будьте первыми</h5>
    </div>
    {% endif %}
{% endblock %}

templates/login.html
{% extends "base.html" %}

{% block content%}

<div class="row">
  <div class="col-lg-5 col-sm-7 mx-auto">
<form method="POST">
  <h3 align="center">Вход</h3>
  {{ form.hidden_tag() }}
  <p>
      {{ form.email.label }}<br>
      {{ form.email(class="form-control", type="email") }}<br>
      {% for error in form.email.errors %}
          <div class="alert alert-danger" role="alert">
              {{ error }}
          </div>
      {% endfor %}
  </p>
  <p>
      {{ form.password.label }}<br>
      {{ form.password(class="form-control", type="password") }}<br>
      {% for error in form.password.errors %}
          <div class="alert alert-danger" role="alert">
              {{ error }}
          </div>
      {% endfor %}
  </p>
  <p>{{ form.remember_me() }} {{ form.remember_me.label }}</p>
  <p>{{ form.submit(type="submit", class="btn btn-primary mx-auto d-block col-lg-3 col-sm-5") }}</p>
  {% if message %}
      <div class="alert alert-warning" role="alert">
        {{message}}
    </div>
  {% endif %}
  <p><a href="{{url_for('auth.sign_up')}}">Нет аккаунта? Зарегистрироваться</a><br><br></p>
</form>
</div>
</div>
{% endblock %}

templates/my_projects.html
{% extends "base.html" %}
{% from "components/project_card.html" import project_card %}

{% block content %}
<a class="btn btn-primary" href="{{url_for('views.home')}}">Назад</a>
    {% if projects %}
    {% for prj in projects %}
    
    <div class="row" style="margin-bottom: 20px;">
        <div class="col-sm-8 mx-auto">
            {{project_card(prj)}}
            <div class="btn-wrapper" style="margin-left: 10px; margin-top: 5px;">
                <a class="btn btn-primary" href="{{url_for('views.view_project', project_id=prj.id)}}">Просмотр</a>
            {% if prj.leader_id != user.id %}
                <a class="btn btn-danger" href="{{url_for('views.leave_project', project_id=prj.id)}}">Покинуть</a>
                <a class="btn btn-success disabled">Вы учавствуете!</a>
            {% else %}
                <a class="btn btn-primary" href="{{url_for('views.edit_project', project_id=prj.id)}}"><i class="bi bi-pencil"></i></a>
                <a class="btn btn-danger" href="{{url_for('views.delete_project', project_id=prj.id)}}"><i class="bi bi-trash"></i></a>
                <a class="btn btn-success disabled">Вы лидер!</a>
            {% endif %}
            </div>
        </div>
    </div>

    {% endfor %}
    {% else %}
    <div class="row">
        <h5 class="text-muted" style="text-align: center">Вы не учавствуете ни в одном проекте</h5>
    </div>
    {% endif %}
{% endblock %}

templates/signup.html
{% extends "base.html" %}

{% block content %}

<div class="row">
<div class="col-lg-5 col-sm-7 mx-auto">
<form action="" method="post">
    <h3 align="center ">Регистрация</h1>
    {{ form.hidden_tag() }}
    <p>
      {{ form.name.label }}<br>
      {{ form.name(class="form-control") }}<br>
      {% for error in form.name.errors %}
          <p class="alert alert-danger" role="alert">
              {{ error }}
          </p>
      {% endfor %}
  </p>
    <p>
        {{ form.email.label }}<br>
        {{ form.email(class="form-control", type="email") }}<br>
        {% for error in form.email.errors %}
            <p class="alert alert-danger" role="alert">
                {{ error }}
            </p>
        {% endfor %}
    </p>
    <p>
        {{ form.password.label }}<br>
        {{ form.password(class="form-control", type="password") }}<br>
        {% for error in form.password.errors %}
            <p class="alert alert-danger" role="alert">
                {{ error }}
            </p>
        {% endfor %}
    </p>
    <p>
        {{ form.password_again.label }}<br>
        {{ form.password_again(class="form-control", type="password") }}<br>
        {% for error in form.password_again.errors %}
            <p class="alert alert-danger" role="alert">
                {{ error }}
            </p>
        {% endfor %}
    </p>
    <p>{{ form.submit(type="submit", class="btn btn-primary mx-auto d-block col-lg-3 col-sm-5") }}</p>
<p><a href="{{url_for('auth.login')}}">Уже есть аккаунт? Войти</a></p>
</form>
</div>
</div>
{% endblock %}

templates/view_project.html
{% extends "base.html" %}
{% from "components/detailed_project_card.html" import detailed_project_card %}

{% block content %}
<a class="btn btn-primary" href="{{url_for('views.my_projects')}}">Назад</a>
    <div class="row" style="margin-bottom: 20px;">
        <div class="col-sm-8 mx-auto">
            {{detailed_project_card(prj, user)}}
            <div class="btn-wrapper" style="margin-left: 10px; margin-top: 5px;">
            {% if prj.leader_id != user.id %}
                <a class="btn btn-danger" href="{{url_for('views.leave_project', project_id=prj.id)}}">Покинуть</a>
            {% else %}
                <a class="btn btn-primary" href="{{url_for('views.edit_project', project_id=prj.id)}}"><i class="bi bi-pencil"></i></a>
                <a class="btn btn-danger" href="{{url_for('views.delete_project', project_id=prj.id)}}"><i class="bi bi-trash"></i></a>
            {% endif %}
            </div>
        </div>
    </div>
{% endblock %}