website/views.py
from flask import Blueprint, render_template, abort, request, url_for, redirect
from flask_login import login_required, current_user
from data import db_session
from data.users import User
from data.projects import Project
from .forms.CreateProjectForm import CreateProjectForm


views = Blueprint("views", __name__, template_folder="../templates")


@views.route("/")
@views.route("/home")
def home():
    db_sess = db_session.create_session()
    projects = db_sess.query(Project).all()

    return render_template("home.html", title='Менеджер проектов', projects=projects, user=current_user)

@views.route("/create-project", methods=['GET', 'POST'])
@login_required
def create_project():
    form = CreateProjectForm()
    
    if form.validate_on_submit():
        db_sess = db_session.create_session()
        user = db_sess.query(User).get(current_user.id)
        
        project = Project(
            name=form.name.data,
            max_members=form.max_members.data,
            description=form.description.data
        )
        project.set_leader(user)
        
        db_sess.add(project)
        db_sess.commit()
        
        return redirect(url_for("views.home"))
    
    return render_template("create_project.html", page_header="Создание проекта", form=form, user=current_user)    


@views.route("/join-project/<int:project_id>")
@login_required
def join_project(project_id):
    db_sess = db_session.create_session()
    project = db_sess.query(Project).get(project_id)
    user = db_sess.query(User).get(current_user.id)
    
    if not project:
        abort(404)
    
    if user in project.members or len(project.members) == project.max_members:
        abort(404)
    
    project.add_member(user)
    db_sess.commit()

    return redirect(url_for("views.home"))


@views.route("/leave-project/<int:project_id>")
def leave_project(project_id):
    db_sess = db_session.create_session()
    project = db_sess.query(Project).get(project_id)
    
    if not project:
        abort(404)
    
    if current_user.id == project.leader_id:
        abort(404)
    
    user = db_sess.query(User).get(current_user.id)
    user.projects.remove(project)
    db_sess.commit()
    return redirect(url_for("views.my_projects"))


@views.route("/delete-project/<int:project_id>")
def delete_project(project_id):
    db_sess = db_session.create_session()
    project = db_sess.query(Project).get(project_id)
    
    if not project:
        abort(404)
    
    if current_user.id != project.leader_id:
        abort(404)
    
    db_sess.delete(project)
    db_sess.commit()
    return redirect(url_for("views.my_projects"))


@views.route("/my-projects")
@login_required
def my_projects():
    db_sess = db_session.create_session()
    user = db_sess.query(User).get(current_user.id)
    print(user.projects)
    return render_template("my_projects.html", projects=user.projects, title="Мои проекты", user=current_user)


@views.route("/edit-project/<int:project_id>", methods=['GET', 'POST'])
@login_required
def edit_project(project_id):
    form = CreateProjectForm()
    
    db_sess = db_session.create_session()
    project = db_sess.query(Project).get(project_id)
    user = db_sess.query(User).get(current_user.id)
    
    if not project:
        abort(404)
    
    if user.id != project.leader_id:
        abort(404)
    
    if form.validate_on_submit():
        project.name = form.name.data
        project.max_members = form.max_members.data
        project.description = form.description.data
        
        db_sess.commit()
        return redirect(url_for("views.my_projects"))
    
    form.name.data = project.name
    form.max_members.data = project.max_members
    form.description.data = project.description
    
    return render_template("create_project.html", page_header="Редактирование проекта", title="Редактирование проекта", form=form, user=current_user)


@views.route("/view-project/<int:project_id>")
@login_required
def view_project(project_id):
    db_sess = db_session.create_session()
    project = db_sess.query(Project).get(project_id)
    user = db_sess.query(User).get(current_user.id)
    
    if not project:
        abort(404)
    
    if user not in project.members:
        abort(404)
    
    return render_template("view_project.html", prj=project, title="Просмотр проекта", user=current_user)


@views.route("/delete-member/<int:project_id>/<int:member_id>")
@login_required
def delete_member(project_id, member_id):
    db_sess = db_session.create_session()
    project = db_sess.query(Project).get(project_id)
    member = db_sess.query(User).get(member_id)
    user = db_sess.query(User).get(current_user.id)
    
    if not project or not member:
        abort(404)
    
    if member.id == user.id:
        abort(404)
    
    if user.id != project.leader_id:
        abort(404)
    
    if member not in project.members:
        abort(404)
    
    project.members.remove(member)
    db_sess.commit()
    
    return redirect(url_for("views.view_project", project_id=project_id))

templates/components/detailed_project_card.html
{% macro detailed_project_card(project, user=None) %}
<div class="card">
    <h5 class="card-header">Название: {{project.name}}</h5>
    <div class="card-body">
      <h6 class="card-title">Лидер: {{project.leader.name}}</h6>
      <h6 class="card-title">Описание:</h6>
      <p class="card-text">{{project.description}}</p>
      <h6 class="card-title">Участников: {{project.members|length}}/{{project.max_members}}</h6>
      {% for member in project.members %}
      <p class="bg-light">
        Участник: №{{loop.index}}<br>
        Имя: {{member.name}}<br>
        Почта: {{member.email}}<br>
        {% if user %}
        {% if user.id == project.leader_id and member.id != project.leader_id %}
            <a class="btn btn-danger btn-sm" href="{{url_for('views.delete_member', project_id=project.id, member_id=member.id)}}"><i class="bi bi-person-x"></i></a>
        {% endif %}
        {% endif %}
      </p>
      {% endfor %}
    </div>
  </div>
{% endmacro %}

templates/components/project_card.html
{% macro project_card(project) %}
<div class="card">
    <h5 class="card-header">Название: {{project.name}}</h5>
    <div class="card-body">
      <h6 class="card-title">Лидер: {{project.leader.name}}</h6>
      <h6 class="card-title">Описание:</h6>
      <p class="card-text">{{project.description}}</p>
      <h6 class="card-title">Участников: {{project.members|length}}/{{project.max_members}}</h6>
    </div>
  </div>
{% endmacro %}

templates/components/toast.html
{% macro toast(name="System", message="", category="") %}
<div class="toast show" role="alert" data-bs-autohide="true" data-bs-delay="5000" aria-live="assertive" aria-atomic="true" style="position: fixed; right: 10px;">
    <div class="toast-header">
    {% set color = "#007aff" %}
    {% if category == "success" %}
        {% set color = "#198754" %}
    {% elif category == "error" %}
        {% set color = "#dc3545" %}
    {% elif category == "warning" %}
        {% set color = '#ffc107' %}
    {% endif %}
    <svg class="bd-placeholder-img rounded me-2" width="20" height="20" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" preserveAspectRatio="xMidYMid slice" focusable="false">
        <rect width="100%" height="100%" fill={{color}}></rect>
    </svg>
      <strong class="me-auto">{{name}}</strong>
      <small class="text-muted">just now</small>
      <button type="button" class="btn-close" data-bs-dismiss="toast" aria-label="Close"></button>
    </div>
    <div class="toast-body">
      {{message}}
    </div>
  </div>
{% endmacro %}

templates/components/user_avatar.html
{% macro user_avatar(id, size=100) %}

{% set filename = "img/user/avatars/avatar_" ~ id ~ ".jpg" %}
{% set alt_file = url_for("static", filename="img/user/avatars/no_avatar.png") %}
<img src="{{url_for('static', filename=filename)}}" alt="Not Found" onerror="this.src='{{alt_file}}';" class="avatar" width={{size}} height={{size}}><br>


{% endmacro %}